### ISSUE TITLE
Opening specific chat from notification

### ISSUE THREAD

**Issue by tomosullivan8** [duytq94/flutter-chat-demo#26]
Hi, 

I know it's just a demo so wont have everything in, but wondered what you thought the best way would be to to open the specific chat from the notification itself.

The best I could think of would be to add the onSelectNotification parameter with: 

```
Future onSelectNotification(String payload) async {
    if (payload != null) {
      debugPrint('notification payload: ' + payload);
    }
    await Navigator.push(
      context,
      new MaterialPageRoute(
          builder: (context) =>
              Chat(
                peerId: //find peerId,
                peerAvatar: //find peerAvatar,
                peerName: //find peerName,
              );
      ),
    );
  }
```

How do I find the specific document references that I require? Is there a way of linking it from the notification received and passing the data all the way through to the function?

Thanks!

**Comment by duytq94** [comment]
Hi,
I think you can use additional data of the notification to send peerId, peerAvatar, peerName.
Geeting them by store more message's properties (add peerAvatar, peerName instead of only peerId as the current implement) so you can get theme later at trigger cloud function and push all of them through notification.
