### ISSUE TITLE
firestore stoarage

### ISSUE THREAD

**Issue by pojoba02** [duytq94/flutter-chat-demo#4]
Uploaded images doesn't seem to show at the frontend simply at the Users end, but it does show at backend(firebase storage). Any thought why that's happening?

**Comment by duytq94** [comment]
Hi @pojoba02 ,
Seem Firebase change syntax, but I fixed this issue, please check the latest code again.
Thanks.

**Comment by pojoba02** [comment]
@duytq94 Thanks for getting back to me, am sorry it wasn't the firebase, from my knowledge the issue might be coming from image Picker. saw the updated code. image Picker doesn't  preview images.

**Comment by duytq94** [comment]
Hi @pojoba02 ,
The issue is can't get url image when you upload success (previous, the image file was uploaded, but we can't get its url). And I just fixed it (the image now can show to the list content chat like video demo).
If you mention about the preview image for user confirm before sending, it is a required new feature, not a bug.
Thanks.

**Comment by pojoba02** [comment]
@duytq94 so what exciting features do you have in mind.

**Comment by duytq94** [comment]
@pojoba02 so what your suggestion at here, require to fix the issue as you said at the first time (image uploaded, but not show in the list content chat) or require a new feature?

**Comment by duytq94** [comment]
Hi @pojoba02 
Actually, to complete the app chat, we need to implement a lot of features, like typing, seen, on/offline status... but at the moment, I don't have time to implement these features.
Thanks.
